server:
  port: 8080

activation:
  stock:
    target: 30

rsa:
  private-key: "file:secrets/keys/rsa-private.pem"
  public-key:  "file:secrets/keys/rsa-public.pem"

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: ${rsa.public-key}
  datasource:
    url: jdbc:postgresql://localhost:12000/gamevault
    username: gamevault_user
    password: gamevault_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true

  data:
    redis:
      host: localhost
      database: 0
      port: 12003
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

app:
  jwt:
    # Replace with ultra-long random string (at least 64 bytes)
    secret: "F3NfhRgpwaw0zWvhLtGnDOHmZomVtzpdt9Js-UkDjGJYTe49kZgKjWoeNCk7VdLU5l5F_eKk5k7nrYzKX8SwA"
    expiration-minutes: 120
  upload:
    path: uploads
    max-file-size: 5MB
    max-request-size: 10MB
  pagination:
    default-page-size: 20
    max-page-size: 100

# MyBatis configuration for forum functionality
mybatis:
  mapper-locations: classpath:mapper/forum/*.xml
  type-aliases-package: com.sg.nusiss.gamevaultbackend.entity.forum
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    lazy-loading-enabled: true
    aggressive-lazy-loading: false

# JWT configuration for forum functionality
jwt:
  secret: "1TuQdaZEWG0U7EiIkrGX1xvbaCJDT7XAsksekHxxFgE="
  expiration: 864000000

# Auth configuration
auth:
  mock:
    enabled: true

# HashId configuration
hashid:
  salt: "forum-backend-2024"